<?php
/**
 * Google Recaptcha for Magento 
 *
 * @package     Yireo_Recaptcha
 * @author      Yireo (http://www.yireo.com/)
 * @copyright   Copyright (c) 2012 Yireo (http://www.yireo.com/)
 * @license     Open Software License
 *
 * This PHTML-template is used when the reCAPTCHA theme-setting is set to "custom"
 * See http://code.google.com/apis/recaptcha/docs/customization.html for more details
 */

?>
<div id="g-recaptcha" class="g-recaptcha" data-sitekey="<?php echo $this->getSiteKey(); ?>"></div>
