<?php
/**
 * Google Recaptcha for Magento
 *
 * @package     Yireo_Recaptcha
 * @author      Yireo (https://www.yireo.com/)
 * @copyright   Copyright 2017 Yireo (https://www.yireo.com/)
 * @license     Open Software License
 *
 * See http://code.google.com/apis/recaptcha/docs/customization.html for more details
 */

$uniqueId = $this->getUniqueId();
$theme = $this->getTheme();
$domId = 'g-recaptcha-'.$uniqueId;
?>
<?php if($this->getBasicMode()) : ?>
<div class="g-recaptcha" data-sitekey="<?= $this->getSiteKey(); ?>"></div>
<?php else: ?>
<div id="<?= $domId; ?>" class="g-recaptcha"></div>
<div id="<?= $domId; ?>-notice" style="display:none;"><?= $this->__('Please complete this CAPTCHA') ?></div>
<script src="<?= $this->getSkinUrl('js/recaptcha/functions.js') ?>"></script>
<script>
    var recaptchaCallback<?= $uniqueId ?> = function() {
        grecaptcha.render('<?= $domId; ?>', {
            'sitekey' : '<?= $this->getSiteKey(); ?>',
            <?php if (!empty($theme)) : ?>'theme' : '<?= $theme; ?>',<?php endif; ?>
            'callback': recaptchaCallbackResponse<?= $uniqueId ?>
        });
    };

    document.observe("dom:loaded", function() {
        Recaptcha.disableAllButtons('<?= $domId; ?>');
    });

    function recaptchaCallbackResponse<?= $uniqueId ?>(response)
    {
        Recaptcha.enableAllButtons('<?= $domId; ?>');
    }
</script>
<?php endif; ?>

<?php if($this->getBasicMode() == false) : ?>
    <script type="text/javascript" src="https://www.google.com/recaptcha/api.js?onload=recaptchaCallback<?= $uniqueId ?>&render=explicit&hl=<?= $this->getLangCode(); ?>" async defer></script>
<?php endif; ?>